version: '3'

services:

  producer:
    build: ./src/producer
    environment:
      KAFKA_BROKER_URL: broker:9092
      SENSOR_TOPIC: queueing.healthcare
      TRANSACTIONS_PER_SECOND: 1000

  consumer:
    build: ./src/consumer
    environment:
      KAFKA_BROKER_URL: broker:9092
      SENSOR_TOPIC: queueing.healthcare

networks:
  default:
    external:
      name: healthcare_data_pipeline
